---
title: "Homework 3"
format: html
author: Liz Peterson
date: 10-23-2024
editor_options: 
  chunk_output_type: console
---

## Load libraries
```{r}
# Read in all necessary libraries
library(tidyverse)
library(here)
library(sf)
library(terra)
library(tmap)
library(spData)
library(spDataLarge)
library(stars)
```

## Read in data
```{r}
# Read in roads data with query to only select highways 
roads <- st_read(here('data','gis_osm_roads_free_1.gpkg'), query = "SELECT * FROM gis_osm_roads_free_1 WHERE fclass='motorway'")

# Read in houses data with query to only select homes 
houses <- st_read(here('data','gis_osm_buildings_a_free_1.gpkg'), query = "SELECT * FROM gis_osm_buildings_a_free_1 WHERE (type IS NULL AND name IS NULL) OR type in ('residential', 'apartments', 'house', 'static_caravan', 'detached')")

# Read in socioeconomic data
texas <- st_read(here('data','ACS_2019_5YR_TRACT_48_TEXAS.gdb'), layer = 'ACS_2019_5YR_TRACT_48_TEXAS')
income <- st_read(here('data','ACS_2019_5YR_TRACT_48_TEXAS.gdb'), layer = "X19_INCOME")

# Check class of these terms to make sure they are correct
class(texas)
class(income)
                 
# Read in lights data --> there are two separate tiles for the same date
seven_05_tile <- read_stars(here("data/VNP46A1/VNP46A1.A2021038.h08v05.001.2021039064328.tif")) 
seven_06_tile <- read_stars(here("data/VNP46A1/VNP46A1.A2021038.h08v06.001.2021039064329.tif"))
sixteen_05_tile <- read_stars(here("data/VNP46A1/VNP46A1.A2021047.h08v05.001.2021048091106.tif"))
sixteen_06_tile <- read_stars(here("data/VNP46A1/VNP46A1.A2021047.h08v06.001.2021048091105.tif"))
```

```{r}
# Merge the two tiles for the same date to create a workable raster
tile_07 <- rast(st_mosaic(seven_05_tile, seven_06_tile))
tile_16 <- rast(st_mosaic(sixteen_05_tile, sixteen_06_tile))
```

```{r}
# Check CRS for what we've read in
print(st_crs(houses) == st_crs(texas))
print(st_crs(tile_07) == st_crs(texas))
print(st_crs(tile_16) == st_crs(texas))
print(st_crs(tile_07) == st_crs(tile_16))
```

```{r}
# Because the two tile rasters have the same CRS, we will use those as the refernce, and update houses and texas to have that same CRS
houses <- st_transform(houses, st_crs(tile_07))
texas <- st_transform(texas, st_crs(tile_07))
```

```{r}
# Run another check to make sure all CRS are now equal
# Create a list of all the rasters, and then create a for loop to make sure they all have the same crs, using the CRS of houses as a reference
rast_list <- list(houses,texas,tile_07,tile_16)
reference <- crs(rast_list[[1]])
for (i in 2:length(rast_list)) {
  print(crs(rast_list[[i]])==reference)
}
```

```{r}
# Reproject the tiles once more, to make sure plotting will work
tile_07 <- project(tile_07, crs(texas))
tile_16 <- project(tile_16, crs(texas))
```

```{r}
# Find the change in night lights intensity (presumably) caused by the storm
# Create a difference raster of the difference in intensity of those two nights
diff_rast <- tile_07 - tile_16
diff_rast[diff_rast < 200] <- NA
# Check again that diff_rast is the same crs as the tiles
diff_rast <- project(diff_rast, crs(tile_07))
```

# Map the night light intensities before and after the storm and the difference
```{r}
# Define my own breaks for our scaling for the first two plots
breaks_tiles <- c(0.1, 0.2, 0.4, 0.6, 1.0, 100, 500)

# Define my own breaks for our scaling for the difference plot
breaks_diff <- c(0.1, 0.3, 0.5)

# Set up grid for plotting (1 row, 3 columns)
par(mfrow=c(1,3))

# Plot using terra, using our defined breaks and colors
plot(tile_07, main = "Night Light Intensity - Before Storm", col = terrain.colors(50), breaks=breaks_tiles, legend = FALSE)
plot(tile_16, main = "Night Light Intensity - After Storm", col = terrain.colors(50), breaks=breaks_tiles, legend = FALSE)
plot(diff_rast, main = "Difference", col = terrain.colors(50), breaks=breaks_diff, legend = FALSE)

# Reset the layout for future
par(mfrow=c(1,1))
```

```{r}
# Vectorize the blackout mask (reclassified difference raster)
# First, convert to polygon so we can use st_as_sf()
blackout_mask_raster <- as.polygons(diff_rast, na.rm = TRUE)

blackout_mask <- blackout_mask_raster %>%
  st_as_sf(as_points = FALSE, merge = TRUE) %>%
  st_make_valid()
```

```{r}
# Initial map of blackout mask to make sure reclassification worked
tm_shape(blackout_mask) +
  tm_polygons()
```

```{r}
# Crop blackout mask to Houston area
# Create a matrix of our coordinates
bounding_box <- st_bbox(c(xmin = -96.5, xmax = -95.4, ymin = 29, ymax = 30.5),
                        crs = st_crs(blackout_mask)) %>%
  st_as_sfc()

# Change both the mask and bbox to have CRS 3083
blackout_mask <- st_transform(blackout_mask, crs = 3083)
bounding_box <- st_transform(bounding_box, crs = 3083)

# Check that CRS updating worked
print(st_crs(blackout_mask) == st_crs(bounding_box))

# Crop the raster
blackout_cropped <- st_intersection(blackout_mask, bounding_box)

# Make sure there are no invalid geometries
blackout_cropped <- st_make_valid(blackout_cropped)
```

```{r}
# Plot blackout cropped data to check analysis worked
tm_shape(blackout_cropped) +
  tm_polygons()
```

```{r}
# Check CRS before transformation
print(st_crs(roads))  # Should match CRS of blackout mask
print(st_crs(blackout_mask))  # Should match CRS of roads
print(st_crs(bounding_box))  # Should match CRS of blackout mask and roads

# Another chance to transform CRS
roads <- st_transform(roads, crs = st_crs(blackout_mask))
blackout_mask <- st_transform(blackout_mask, crs = st_crs(roads))
bounding_box <- st_transform(bounding_box, crs = st_crs(blackout_mask))
```

```{r}
# Check if all layers align visually
tm_shape(roads) +
  tm_lines() +
  tm_layout() +
tm_shape(blackout_cropped) +
  tm_borders(col = "lightblue") +
  tm_layout()

```

## Exclude highways from the cropped blackout mask
```{r}
# Create a 200-meter buffer around highways & make sure its crs is correct
roads_buffer <- st_buffer(roads, dist = 200)
roads_buffer <- st_transform(roads_buffer, st_crs(blackout_cropped))

# Make sure there are no issues with invalid geometries
roads_buffer <- st_make_valid(roads_buffer)
```

```{r}
# Plot roads buffer to confirm it worked
tm_shape(roads_buffer) +
  tm_polygons()
```

```{r}
# Use st_union to combine geometries in the buffer
roads_buffer_union <- st_union(roads_buffer)

tm_shape(roads_buffer_union) +
  tm_polygons()
```

```{r}
# Exclude areas within 200m of highways using st_difference
blackout_no_highways <- st_difference(blackout_cropped, roads_buffer_union)

# Make sure there are no invalid geometries
blackout_no_highways <- st_make_valid(blackout_no_highways)

# Check result by plotting
tm_shape(blackout_no_highways) +
  tm_polygons()
```

## Identify homes likely impacted by blackouts
```{r}
# Make sure that houses has the same crs as the blackout_no_highways
houses <- st_transform(houses, st_crs(blackout_no_highways))

# Use bracket subsetting to filter
houses_blackout <- houses[blackout_no_highways, ]
```

```{r}
# Plot houses_blackout to see if it worked
tm_shape(blackout_cropped) +
  tm_borders() +
tm_shape(houses_blackout) +
  tm_bubbles(col = "red", size = 0.1)
```

## Identify the census tracts likely impacted by blackout
```{r}

```


